npm install cookie-parser
npm install cheerio
npm install referrer-policy
npm install vcodes.js
npm install discord.js
npm uninstall discord.js
npm i discord.js@12.5.3
npm install quick.db
npm i canvas
npm install discord.js
npm install
npm install node:events
npm install node-events
npm install node-events
npm install discord.js
npm i discord.js
npm i discord.js@12.5.3
pnpm install discord.js
pnpm install node:events
pnpm install node-events
npm install express
npm install express
npm i x
npm install croxydb
npm install quick.db
pnpm install quick.db
npm install discord.js
npm install quick.db
npm install discord.js
npm install wio.db
npm install moment
npm install moment-duration-format
npm install parse-ms
npm install dblapi.js
npm install express
npm install node-superfetch
rm -rf .git
rm -rf .git
rm -rf .git
rm -rf .git
rm -rf .git
npm install discord-giveaways
npm install cleverbot.io
npm install discord-buttons
npm install /app/handlers/functions
npm install tcmb-doviz
npm install discord.js-reaction-menu
npm install croxydb
npm install chance
npm install discord-embeds-pages-buttons
npm install request
npm install nukleon
npm install best-tools
npm install best-tools
pnpm install best-tools
npm install best-tools
npm install discord-logs
